---
apiVersion: v1
kind: Service
metadata:
  name: openmrs-svc
  labels:
    svc: lb
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: openmrs
    version: "1.0"
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs-rs
  labels:
    app: openmrs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      containers:
        - name: openmrs
          image: docker1196/myopenmrs:1.0
          ports:
          - containerPort: 8080
